title: Raldamain
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
lang: es

defaults:
  -
    scope:
      path: "characters"
    values:
      layout: character
  -
    scope:
      path: "locations"
    values:
      layout: character
  -
    scope:
      path: "factions"
    values:
      layout: character
  -
    scope:
      path: "events"
    values:
      layout: character
  -
    scope:
      path: "rules"
    values:
      layout: rule


# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
kramdown:
  input: GFM
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-coffeescript
  - jekyll-default-layout
  - jekyll-gist
  - jekyll-github-metadata
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-titles-from-headings
  - jekyll-relative-links
  
  
exclude:
  - Gemfile
  - Gemfile.lock
