title: Raldamain
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/" # the subpath of your site, e.g. /blog/
lang: es

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      category: ""
      lang: "es"
  -
    scope:
      path: "en"
    values:
      lang: en
      layout: rule
  -
    scope:
      path: "characters"
    values:
      layout: character
  -
    scope:
      path: "locations"
    values:
      layout: character
  -
    scope:
      path: "factions"
    values:
      layout: character
  -
    scope:
      path: "world"
    values:
      layout: rule
  -
    scope:
      path: "rules"
    values:
      layout: rule
  -
    scope:
      path: "campaign"
    values:
      layout: campaign

# Build settings
safe: false # use custom plugins
markdown: kramdown
kramdown:
  input: GFM
sass:
  indentWidth: 4
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-include-cache
  
  
exclude:
  - Gemfile
  - Gemfile.lock
