"""
Raldamain Item Generator
========================
Generates 100+ item JSON files in data/equipment/
Run: python tools/generate_items.py
"""
import os, json

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
OUT_DIR = os.path.join(os.path.dirname(SCRIPT_DIR), "data", "equipment")

def write_item(item):
    path = os.path.join(OUT_DIR, f"{item['id']}.json")
    with open(path, "w", encoding="utf-8") as f:
        json.dump(item, f, indent=2, ensure_ascii=False)

def weapon(id, name, subtype, rarity, damage, dmgType, price, desc, range_="Cuerpo a cuerpo", props=None, abilities=None, lore=None, type_="Arma"):
    item = {"id": id, "name": name, "type": type_, "subtype": subtype, "rarity": rarity,
            "image": f"{id}.jpg", "description": desc, "damage": damage, "damageType": dmgType,
            "price": price, "range": range_}
    if props: item["properties"] = props
    if abilities: item["abilities"] = abilities
    if lore: item["lore"] = lore
    return item

def armor(id, name, subtype, rarity, defense, price, desc, props=None, abilities=None, penalties=None, lore=None, type_="Armadura"):
    item = {"id": id, "name": name, "type": type_, "subtype": subtype, "rarity": rarity,
            "image": f"{id}.jpg", "description": desc, "defense": str(defense), "price": price}
    if props: item["properties"] = props
    if abilities: item["abilities"] = abilities
    if penalties: item["penalties"] = penalties
    if lore: item["lore"] = lore
    return item

def magic_item(id, name, subtype, rarity, price, desc, props=None, abilities=None, lore=None):
    item = {"id": id, "name": name, "type": "Objeto Mágico", "subtype": subtype, "rarity": rarity,
            "image": f"{id}.jpg", "description": desc, "price": price}
    if props: item["properties"] = props
    if abilities: item["abilities"] = abilities
    if lore: item["lore"] = lore
    return item

def ab(name, cost, uses, desc):
    return {"name": name, "cost": cost, "uses": uses, "description": desc}

# ═══════════════════════════════════════════════════════════════
# ALL ITEMS
# ═══════════════════════════════════════════════════════════════

ITEMS = []

# ─── COMMON WEAPONS ───
ITEMS += [
    weapon("espada_corta", "Espada Corta", "Arma Simple Cuerpo a Cuerpo", "Común",
           "1d6 + FUE/DES", "Cortante", "0 CR",
           "Una hoja recta y ligera de unos 60 centímetros. Popular entre soldados y aventureros por su versatilidad en espacios reducidos.",
           props=["<b>Ligera</b>: Puedes usar FUE o DES para tiros de ataque"]),
    weapon("hacha_mano", "Hacha de Mano", "Arma Simple Cuerpo a Cuerpo", "Común",
           "1d6 + FUE", "Cortante", "0 CR",
           "Un hacha pequeña con mango de madera, tan útil para cortar leña como para el combate. Puede arrojarse con precisión.",
           range_="Cuerpo a cuerpo o arrojadiza (distancia media)",
           props=["<b>Arrojadiza</b>: Puede lanzarse a distancia media"]),
    weapon("maza", "Maza", "Arma Simple Cuerpo a Cuerpo", "Común",
           "1d6 + FUE", "Contundente", "0 CR",
           "Una cabeza de metal pesada montada sobre un mango corto de madera reforzada. Ideal contra enemigos acorazados."),
    weapon("garrote", "Garrote", "Arma Simple Cuerpo a Cuerpo", "Común",
           "1d6 + FUE", "Contundente", "0 CR",
           "Un palo grueso y tosco, a veces reforzado con clavos o hierro. El arma más primitiva pero sorprendentemente efectiva."),
    weapon("lanza", "Lanza", "Arma Marcial Cuerpo a Cuerpo", "Común",
           "1d10 + FUE", "Perforante", "0 CR",
           "Un asta de madera rematada con una punta de acero. Su alcance superior permite mantener a los enemigos a distancia.",
           range_="Alcance cercano",
           props=["<b>Alcance</b>: Ataca a distancia cercana en vez de adyacente", "<b>Dos manos</b>: Requiere ambas manos para usarse"]),
    weapon("jabalina", "Jabalina", "Arma Simple a Distancia", "Común",
           "1d8 + FUE", "Perforante", "0 CR",
           "Un dardo largo y equilibrado diseñado para ser arrojado. Usado por cazadores y legiones desde tiempos inmemoriales.",
           range_="Distancia cercana o media",
           props=["<b>Arrojadiza</b>: Diseñada para lanzarse"]),
    weapon("arco_corto", "Arco Corto", "Arma Simple a Distancia", "Común",
           "1d8 + DES", "Perforante", "0 CR",
           "Un arco compacto de madera flexible, ideal para emboscadas y combate montado. Menor alcance que el arco largo pero más manejable.",
           range_="Distancia media",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Munición</b>: Requiere flechas"]),
    weapon("ballesta", "Ballesta", "Arma Marcial a Distancia", "Común",
           "1d10 + DES", "Perforante", "1 CR",
           "Un arma mecánica que dispara virotes con fuerza devastadora. Requiere recarga pero no necesita gran fuerza física.",
           range_="Distancia lejana",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Recarga</b>: Cuesta 1 acción recargar", "<b>Munición</b>: Requiere virotes"]),
    weapon("espada_ropera", "Espada Ropera", "Arma Marcial Cuerpo a Cuerpo", "Común",
           "1d8 + DES", "Perforante", "1 CR",
           "Una hoja larga y delgada diseñada para estocadas precisas. El arma predilecta de duelistas y espadachines refinados.",
           props=["<b>Precisión</b>: Usa DES para tiros de ataque y daño"]),
    weapon("mandoble", "Mandoble", "Arma Marcial Cuerpo a Cuerpo", "Común",
           "2d6 + FUE", "Cortante", "2 CR",
           "Una espada enorme de hoja ancha que requiere ambas manos. Capaz de partir armaduras y escudos con facilidad.",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Pesada</b>: Desventaja en tiradas de Parada"]),
    weapon("gran_hacha", "Gran Hacha", "Arma Marcial Cuerpo a Cuerpo", "Común",
           "2d8 + FUE", "Cortante", "2 CR",
           "Un hacha de guerra con una hoja inmensa montada en un asta larga. Favorita de berserkers y ejecutores.",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Pesada</b>: Desventaja en tiradas de Parada"]),
    weapon("gran_maza", "Gran Maza", "Arma Marcial Cuerpo a Cuerpo", "Común",
           "2d8 + FUE", "Contundente", "2 CR",
           "Un mazo de guerra con cabeza de hierro fundido. Cada golpe resuena como un trueno y puede destrozar huesos y piedra.",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Pesada</b>: Desventaja en tiradas de Parada"]),
    weapon("latigo", "Látigo", "Arma Simple Cuerpo a Cuerpo", "Común",
           "1d6 + DES", "Contundente", "0 CR",
           "Una tira de cuero trenzado de tres metros de largo. Puede atrapar extremidades y desarmar oponentes.",
           range_="Alcance cercano",
           props=["<b>Alcance</b>: Ataca a distancia cercana", "<b>Desarme</b>: Puedes intentar desarmar en vez de hacer daño"]),
    weapon("pistola_mano", "Pistola de Mano", "Arma de Fuego", "Común",
           "2d6 + DES", "Perforante", "2 CR",
           "Un arma de fuego compacta con mecanismo de chispa. Devastadora a corta distancia pero lenta de recargar y propensa a fallos.",
           range_="Distancia media",
           props=["<b>Recarga</b>: Cuesta 2 acciones recargar", "<b>Explosiva</b>: En un 1 natural, el arma se encasquilla y no puede usarse hasta repararla"]),
    weapon("mosqueton", "Mosquetón", "Arma de Fuego", "Común",
           "2d8 + DES", "Perforante", "3 CR",
           "Un arma de fuego larga con cañón estriado. Su poder de penetración supera a cualquier arco, pero es ruidosa y lenta.",
           range_="Distancia lejana",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Recarga</b>: Cuesta 2 acciones recargar", "<b>Explosiva</b>: En un 1 natural, el arma se encasquilla"]),
]

# ─── COMMON ARMOR ───
ITEMS += [
    armor("armadura_acolchada", "Armadura Acolchada", "Armadura Ligera", "Común",
          1, "0 CR",
          "Capas de tela gruesa acolchada y cosida. Ofrece protección mínima pero no restringe el movimiento en absoluto."),
    armor("cota_anillas", "Cota de Anillas", "Armadura Media", "Común",
          5, "1 CR",
          "Anillas de metal entrelazadas sobre una base de cuero. Buen compromiso entre protección y movilidad para guerreros versátiles.",
          penalties="-4 a tiradas de DES. Desventaja en tiradas de magia si FUE < 4."),
    armor("armadura_completa", "Armadura Completa", "Armadura Pesada", "Común",
          9, "3 CR",
          "Placas de acero que cubren todo el cuerpo, incluyendo casco cerrado y guanteletes articulados. La máxima protección mundana posible.",
          penalties="-6 a tiradas de DES. Velocidad -3m. Desventaja en tiradas de magia si FUE < 6."),
    armor("escudo_torre", "Escudo de Torre", "Escudo", "Común",
          3, "1 CR",
          "Un escudo rectangular de madera reforzada con hierro que cubre casi todo el cuerpo. Usado por formaciones militares.",
          props=["<b>Cobertura</b>: Puedes usar 1 acción para atrincherarte, ganando +2 DEF adicional hasta tu siguiente turno"],
          penalties="No puedes usar armas a dos manos mientras lo portas."),
]

# ─── COMMON MAGIC ITEMS ───
ITEMS += [
    magic_item("pocion_vigor", "Poción de Vigor", "Poción", "Común", "1/3 CR",
               "Un líquido ámbar burbujeante que sabe a miel y especias. Restaura la energía del cuerpo casi al instante.",
               props=["<b>Consumible:</b> Se destruye al usarse"],
               abilities=[ab("Restaurar Vigor", "1 acción", "Una vez",
                            "Recuperas 3 puntos de Vigor o Chi inmediatamente.")]),
    magic_item("antidoto", "Antídoto Universal", "Poción", "Común", "1/3 CR",
               "Un frasco de líquido verde esmeralda con un sabor intensamente amargo. Neutraliza la mayoría de venenos conocidos.",
               props=["<b>Consumible:</b> Se destruye al usarse"],
               abilities=[ab("Neutralizar Veneno", "1 acción", "Una vez",
                            "Elimina un efecto de veneno que te afecte actualmente.")]),
    magic_item("piedra_luz", "Piedra de Luz", "Maravilloso", "Común", "1/4 CR",
               "Una pequeña piedra cristalina que emite una luz suave y constante cuando se sostiene. Común entre mineros y exploradores.",
               abilities=[ab("Iluminar", "Pasiva", "Permanente",
                            "Emite luz brillante en un radio de 6m y luz tenue en 12m adicionales. Puede apagarse cubriéndola.")]),
    magic_item("cuerda_seda_aracnida", "Cuerda de Seda Arácnida", "Maravilloso", "Común", "1/2 CR",
               "Una cuerda de 15 metros tejida con seda de araña gigante. Extremadamente resistente y ligera.",
               props=["<b>Irrompible:</b> No puede ser cortada por medios no mágicos",
                      "<b>Ligera:</b> Pesa la mitad que una cuerda normal"]),
    magic_item("tiza_arcana", "Tiza Arcana", "Maravilloso", "Común", "1/4 CR",
               "Una barra de tiza imbuida con polvo de cristal de Chi. Los círculos dibujados con ella brillan tenuemente.",
               props=["<b>Consumible:</b> 10 usos"],
               abilities=[ab("Círculo de Protección", "1 minuto", "10 usos",
                            "Dibuja un círculo de 3m que otorga +1 a salvaciones contra efectos mágicos a quienes estén dentro.")]),
]

# ─── UNCOMMON WEAPONS ───
ITEMS += [
    weapon("espada_relampago", "Espada del Relámpago", "Arma Marcial Cuerpo a Cuerpo", "Poco Común",
           "1d8 + FUE + 1d6 eléctrico", "Cortante + Eléctrico", "4 CR",
           "Una espada larga cuya hoja crepita con arcos de electricidad. El aire a su alrededor huele a ozono.",
           type_="Arma Mágica",
           props=["<b>Conductora:</b> El daño eléctrico adicional ignora resistencia a cortante"],
           abilities=[ab("Descarga", "1 acción + 1 Chi", "3/día",
                        "Tu siguiente ataque libera una descarga que salta a un enemigo adicional dentro de 3m, infligiendo 1d6 eléctrico.")]),
    weapon("hacha_escarcha", "Hacha de Escarcha", "Arma Marcial Cuerpo a Cuerpo", "Poco Común",
           "1d10 + FUE + 1d6 frío", "Cortante + Frío", "4 CR",
           "Un hacha de batalla con la hoja permanentemente cubierta de escarcha azulada. El frío que emana entumece las manos.",
           type_="Arma Mágica",
           props=["<b>Gélida:</b> Los objetivos golpeados tienen -1m de velocidad hasta el fin de su siguiente turno"]),
    weapon("arco_viento", "Arco del Viento", "Arma Marcial a Distancia", "Poco Común",
           "1d10 + DES", "Perforante", "3 CR",
           "Un arco élfico tallado en madera de fresno blanco. Las flechas disparadas por él viajan envueltas en corrientes de aire.",
           range_="Distancia lejana",
           type_="Arma Mágica",
           props=["<b>Viento Favorable:</b> Las flechas no se ven afectadas por viento ni clima",
                  "<b>Dos manos</b>: Requiere ambas manos"]),
    weapon("martillo_trueno", "Martillo del Trueno Menor", "Arma Marcial Cuerpo a Cuerpo", "Poco Común",
           "1d10 + FUE + 1d6 sónico", "Contundente + Sónico", "4 CR",
           "Un martillo de guerra con runas grabadas que resuenan con cada impacto. El sonido del golpe aturde a los cercanos.",
           type_="Arma Mágica",
           abilities=[ab("Onda de Choque", "1 acción + 1 Vigor", "3/día",
                        "Al golpear, todos los enemigos en 3m deben superar PHYS o ser empujados 3m.")]),
    weapon("daga_veneno", "Daga Envenenada de Kresh", "Arma Simple Cuerpo a Cuerpo", "Poco Común",
           "1d6 + DES + 1d6 veneno", "Perforante + Veneno", "3 CR",
           "Una daga delgada con una hoja acanalada que secretea un veneno verdoso. Forjada en los talleres clandestinos de Kresh.",
           range_="Cuerpo a cuerpo o arrojadiza (distancia media)",
           type_="Arma Mágica",
           props=["<b>Tóxica:</b> El veneno se regenera mágicamente. El objetivo debe superar PHYS o quedar envenenado 1 turno"]),
    weapon("lanza_luz", "Lanza de Luz", "Arma Marcial Cuerpo a Cuerpo", "Poco Común",
           "1d10 + FUE + 1d6 radiante", "Perforante + Radiante", "4 CR",
           "Una lanza de plata pulida cuya punta emite un resplandor dorado. Especialmente efectiva contra no-muertos y demonios.",
           range_="Alcance cercano",
           type_="Arma Mágica",
           props=["<b>Sagrada:</b> Inflige daño radiante adicional. Contra no-muertos y demonios, el dado de daño radiante es 1d10"]),
    weapon("ballesta_repeticion", "Ballesta de Repetición", "Arma Marcial a Distancia", "Poco Común",
           "1d10 + DES", "Perforante", "5 CR",
           "Una ballesta mecánica con un cargador de cinco virotes y mecanismo de recarga automática. Ingeniería iskariana de vanguardia.",
           range_="Distancia lejana",
           type_="Arma Mágica",
           props=["<b>Cargador:</b> Contiene 5 virotes. No necesita acción de recarga hasta agotar el cargador",
                  "<b>Dos manos</b>: Requiere ambas manos"]),
    weapon("cadena_espinada", "Cadena Espinada", "Arma Marcial Cuerpo a Cuerpo", "Poco Común",
           "1d10 + FUE", "Contundente + Perforante", "3 CR",
           "Una cadena de acero negro cubierta de púas afiladas. Usada por gladiadores y carceleros como instrumento de sometimiento.",
           range_="Alcance cercano",
           type_="Arma Mágica",
           props=["<b>Alcance:</b> Ataca a distancia cercana", "<b>Atrapar:</b> Al golpear, puedes intentar agarrar al objetivo (PHYS del objetivo para escapar)",
                  "<b>Dos manos</b>: Requiere ambas manos"]),
]

# ─── UNCOMMON ARMOR ───
ITEMS += [
    armor("cota_elfos", "Cota de los Elfos", "Armadura Ligera", "Poco Común",
          4, "4 CR",
          "Una malla finísima tejida por artesanos elfos con hilos de mithrilo. Tan ligera como la seda pero resistente como el acero.",
          type_="Armadura Mágica",
          props=["<b>Élfica:</b> No impone penalizaciones a DES ni a tiradas de magia",
                 "<b>Sigilosa:</b> No impone desventaja en sigilo"]),
    armor("armadura_reforzada", "Armadura de Cuero Reforzado", "Armadura Ligera", "Poco Común",
          3, "3 CR",
          "Cuero endurecido con placas de acero incrustadas en puntos vitales. Ofrecida a exploradores veteranos del imperio.",
          type_="Armadura Mágica"),
    armor("peto_gladiador", "Peto del Gladiador", "Armadura Media", "Poco Común",
          5, "3 CR",
          "Un pectoral de bronce pulido con hombreras decorativas. Diseñado para la arena: máxima protección frontal sin restringir movimiento ofensivo.",
          type_="Armadura Mágica",
          props=["<b>Exhibicionista:</b> +1 a tiradas de Presencia e Intimidación mientras lo vistes"],
          penalties="-2 a tiradas de DES (en vez de -4)."),
    armor("escudo_guardian", "Escudo Guardián", "Escudo", "Poco Común",
          2, "4 CR",
          "Un escudo de acero con un ojo grabado en su centro que brilla tenuemente. Reacciona ante amenazas antes de que el portador las perciba.",
          type_="Armadura Mágica",
          abilities=[ab("Proteger Aliado", "1 reacción", "Ilimitado",
                       "Cuando un aliado adyacente recibe un ataque, puedes interponer el escudo, otorgándole tu DEF de escudo para esa tirada.")]),
    armor("armadura_sombria", "Armadura Sombría", "Armadura Ligera", "Poco Común",
          2, "4 CR",
          "Cuero negro que parece absorber la luz a su alrededor. Los bordes se difuminan en sombras que ocultan la silueta del portador.",
          type_="Armadura Mágica",
          props=["<b>Umbral:</b> Ventaja en tiradas de Sigilo en penumbra u oscuridad"]),
]

# ─── UNCOMMON MAGIC ITEMS ───
ITEMS += [
    magic_item("guantes_fuerza", "Guantes de Fuerza de Ogro", "Maravilloso", "Poco Común", "4 CR",
               "Guantes de cuero grueso imbuidos con la esencia de un ogro. Al ponérselos, los músculos del portador se hinchan visiblemente.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Fuerza Sobrenatural", "Pasiva", "Permanente",
                            "Tu estadística de FUE se considera 4 mientras lleves estos guantes (no tiene efecto si tu FUE ya es 4 o mayor).")]),
    magic_item("botas_sigilo", "Botas del Sigilo", "Maravilloso", "Poco Común", "3 CR",
               "Botas de cuero suave con suelas encantadas que amortiguan cualquier sonido. Ni la grava ni las hojas secas revelan tus pasos.",
               abilities=[ab("Pasos Silenciosos", "Pasiva", "Permanente",
                            "Tus pasos no producen sonido. Ventaja en tiradas de Sigilo relacionadas con ruido.")]),
    magic_item("capa_resistencia", "Capa de Resistencia", "Maravilloso", "Poco Común", "4 CR",
               "Una capa gruesa de lana carmesí con bordados protectores en hilo de plata. Emana un calor reconfortante.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Resistencia Elemental", "Pasiva", "Permanente",
                            "Elige un tipo de daño elemental (fuego, frío, eléctrico o sónico) al sintonizar. Ganas resistencia a ese tipo de daño.")]),
    magic_item("amuleto_escudo", "Amuleto del Escudo Arcano", "Maravilloso", "Poco Común", "3 CR",
               "Un medallón de cristal azul con un símbolo de escudo grabado. Brilla intensamente cuando su portador está en peligro.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Barrera Arcana", "1 reacción + 1 Chi", "3/día",
                            "Cuando recibes daño, puedes activar el amuleto para reducir el daño en 1d8.")]),
    magic_item("gafas_noche", "Gafas de Visión Nocturna", "Maravilloso", "Poco Común", "3 CR",
               "Lentes de cristal ahumado montadas en un marco de cobre con grabados rúnicos. El mundo se ilumina en tonos verdes al usarlas.",
               abilities=[ab("Visión en la Oscuridad", "Pasiva", "Permanente",
                            "Puedes ver en oscuridad total hasta 18m como si fuera luz tenue.")]),
    magic_item("bolsa_conservacion", "Bolsa de Conservación", "Maravilloso", "Poco Común", "3 CR",
               "Una bolsa de cuero aparentemente normal pero cuyo interior es mucho más grande de lo que debería. El espacio interior está en estasis.",
               abilities=[ab("Espacio Extradimensional", "Pasiva", "Permanente",
                            "El interior puede contener hasta 250 kg en un espacio de 1m cúbico. Los objetos dentro no se deterioran ni pesan para el portador.")]),
    magic_item("piedra_comunicacion", "Piedras de Comunicación", "Maravilloso", "Poco Común", "3 CR",
               "Un par de piedras lisas de cuarzo rosa conectadas mágicamente. Al hablar cerca de una, la otra reproduce las palabras.",
               abilities=[ab("Comunicación", "Pasiva", "Permanente",
                            "Permite hablar con quien posea la piedra emparejada a una distancia máxima de 1 km. Funciona a través de barreras físicas.")]),
    magic_item("pocion_curacion_mayor", "Poción de Curación Mayor", "Poción", "Poco Común", "1 CR",
               "Un líquido carmesí intenso con destellos dorados. Más concentrada que la poción básica, su efecto es notablemente más potente.",
               props=["<b>Consumible:</b> Se destruye al usarse"],
               abilities=[ab("Curación Mayor", "1 acción", "Una vez",
                            "Recuperas 10 puntos de Vitalidad y reduces una herida permanente por un paso.")]),
    magic_item("pocion_velocidad", "Poción de Velocidad", "Poción", "Poco Común", "1 CR",
               "Un líquido plateado que se mueve dentro del frasco como mercurio vivo. Al beberla, el mundo parece ralentizarse.",
               props=["<b>Consumible:</b> Se destruye al usarse"],
               abilities=[ab("Celeridad", "1 acción", "Una vez",
                            "Durante 1 minuto, tu velocidad se duplica y ganas 1 acción adicional por turno (solo para movimiento o ataques con arma).")]),
    magic_item("pocion_fuerza_gigante", "Poción de Fuerza de Gigante", "Poción", "Poco Común", "1 CR",
               "Un líquido marrón turbio con sedimentos que brillan como oro. Sabe a tierra y hierro, pero otorga una fuerza descomunal.",
               props=["<b>Consumible:</b> Se destruye al usarse"],
               abilities=[ab("Fuerza de Gigante", "1 acción", "Una vez",
                            "Durante 1 minuto, tu FUE se considera 6 (sin efecto si ya es 6+) y tu daño cuerpo a cuerpo gana +1d6.")]),
    magic_item("linterna_reveladora", "Linterna Reveladora", "Maravilloso", "Poco Común", "3 CR",
               "Una linterna de bronce con cristales prismáticos que proyecta luz en un cono. Bajo su brillo, lo oculto se revela.",
               abilities=[ab("Luz Reveladora", "1 acción", "Ilimitado",
                            "La luz revela criaturas y objetos invisibles, ilusiones y pasajes ocultos en un cono de 9m.")]),
    magic_item("amuleto_traduccion", "Amuleto del Políglota", "Maravilloso", "Poco Común", "3 CR",
               "Un medallón con docenas de diminutas runas en idiomas olvidados. Vibra suavemente cuando se habla cerca de él.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Comprensión Universal", "Pasiva", "Permanente",
                            "Comprendes cualquier idioma hablado que escuches. No otorga la capacidad de hablar o leer dicho idioma.")]),
]

# ─── RARE WEAPONS ───
ITEMS += [
    weapon("espada_danzante", "Espada Danzante", "Arma Marcial Cuerpo a Cuerpo", "Rara",
           "1d8 + FUE", "Cortante", "8 CR",
           "Una espada larga de hoja iridiscente que parece tener voluntad propia. Cuando se libera, flota y combate sola.",
           type_="Arma Mágica",
           abilities=[ab("Danza de la Espada", "1 acción + 2 Chi", "1/día",
                        "La espada flota y ataca por sí sola durante 1 minuto, usando tu bonificador de ataque. Puedes dirigirla como acción bonus a un objetivo dentro de 9m.")]),
    weapon("arco_fuego_solar", "Arco del Fuego Solar", "Arma Marcial a Distancia", "Rara",
           "1d10 + DES + 1d8 fuego", "Perforante + Fuego", "10 CR",
           "Un arco de madera dorada que arde sin consumirse. Las flechas que dispara se envuelven en llamas al salir del arco.",
           range_="Distancia lejana",
           type_="Arma Mágica",
           props=["<b>Flechas Ígneas:</b> Las flechas son de fuego puro. No requiere munición física",
                  "<b>Dos manos</b>: Requiere ambas manos"],
           abilities=[ab("Flecha Solar", "2 acciones + 2 Chi", "1/día",
                        "Disparas una flecha de fuego solar que explota al impactar. Todos en un radio de 6m del objetivo deben superar PHYS o recibir 3d10 fuego.")]),
    weapon("martillo_terremoto", "Martillo del Terremoto", "Arma Marcial Cuerpo a Cuerpo", "Rara",
           "1d10 + FUE + 1d8 contundente", "Contundente", "10 CR",
           "Un martillo de guerra con la cabeza tallada en roca volcánica y runas de tierra. El suelo tiembla con cada golpe.",
           type_="Arma Mágica",
           abilities=[ab("Temblor", "2 acciones + 2 Vigor", "2/día",
                        "Golpeas el suelo. Todos los enemigos en 6m deben superar PHYS o caer tropezados y recibir 2d8 contundente.")]),
    weapon("espada_ropera_duelo", "Espada del Duelo Perfecto", "Arma Marcial Cuerpo a Cuerpo", "Rara",
           "1d8 + DES", "Perforante", "8 CR",
           "Una espada ropera de manufactura exquisita con guarda en forma de espiral. Responde a los movimientos del portador como una extensión de su cuerpo.",
           type_="Arma Mágica",
           props=["<b>Precisión:</b> Usa DES para ataque y daño", "<b>Riposte:</b> Cuando un enemigo falla un ataque cuerpo a cuerpo contra ti, puedes hacer un ataque de oportunidad como reacción"],
           abilities=[ab("Estocada Perfecta", "1 acción + 1 Vigor", "3/día",
                        "Tu siguiente ataque tiene Ventaja y si impacta, inflige daño crítico automáticamente (dados de daño duplicados).")]),
    weapon("tridente_mareas", "Tridente de las Mareas", "Arma Marcial Cuerpo a Cuerpo", "Rara",
           "1d10 + FUE + 1d8 frío", "Perforante + Frío", "10 CR",
           "Un tridente forjado en coral petrificado y acero marino. Gotea agua salada constantemente y huele a océano profundo.",
           range_="Alcance cercano o arrojadiza (distancia media)",
           type_="Arma Mágica",
           props=["<b>Alcance:</b> Ataca a distancia cercana", "<b>Arrojadiza:</b> Regresa mágicamente a tu mano al final del turno"],
           abilities=[ab("Ola Aplastante", "2 acciones + 2 Chi", "1/día",
                        "Invocas una ola de agua que barre un cono de 9m. Todos deben superar PHYS o recibir 3d8 frío y ser empujados 6m.")]),
    weapon("guadana_almas", "Guadaña de las Almas", "Arma Marcial Cuerpo a Cuerpo", "Rara",
           "2d6 + FUE + 1d8 necrótico", "Cortante + Necrótico", "12 CR",
           "Una guadaña de hoja negra que emite un aura de frío mortal. Las almas de los caídos son visibles como niebla alrededor de la hoja.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Vampírica:</b> Recuperas Vitalidad igual a la mitad del daño necrótico infligido",
                  "<b>Sintonización</b>: Requiere sintonización por un usuario de Nigromancia o Magia Sombría"]),
    weapon("mandoble_tormenta", "Mandoble de la Tormenta", "Arma Marcial Cuerpo a Cuerpo", "Rara",
           "2d6 + FUE + 1d8 eléctrico", "Cortante + Eléctrico", "12 CR",
           "Un mandoble cuya hoja está forjada con metal celeste que canaliza tormentas. Rayos serpentean por su filo durante el combate.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>"],
           abilities=[ab("Llamar al Rayo", "2 acciones + 3 Chi", "1/día",
                        "Invocas un rayo del cielo sobre un punto a 18m. Todos en un radio de 3m deben superar PHYS o recibir 4d10 eléctrico (mitad en éxito).")]),
    weapon("gran_hacha_carnicero", "Gran Hacha del Carnicero", "Arma Marcial Cuerpo a Cuerpo", "Rara",
           "2d8 + FUE", "Cortante", "8 CR",
           "Un hacha brutal con una hoja dentada y manchas de óxido que nunca se limpian. Cada golpe desgarra la carne de forma terrible.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Pesada</b>: Desventaja en tiradas de Parada",
                  "<b>Brutal:</b> Cuando haces daño crítico, tira los dados de daño tres veces en vez de dos"]),
]

# ─── RARE ARMOR ───
ITEMS += [
    armor("armadura_sombras", "Armadura de las Sombras", "Armadura Ligera", "Rara",
          3, "8 CR",
          "Cuero teñido con esencia del Plano Sombrío. Las sombras se adhieren al portador, dificultando que sea visto o alcanzado.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>"],
          abilities=[ab("Paso Sombrío", "1 acción + 1 Chi", "2/día",
                       "Te fundes con las sombras y te teleportas hasta 9m a otra zona en penumbra u oscuridad que puedas ver.")]),
    armor("coraza_espejada", "Coraza Espejada", "Armadura Media", "Rara",
          6, "10 CR",
          "Una coraza de acero pulido como un espejo perfecto. Los ataques mágicos se reflejan en su superficie bruñida.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>"],
          abilities=[ab("Reflejo Arcano", "1 reacción + 1 Chi", "2/día",
                       "Cuando eres objetivo de un ataque mágico a distancia, puedes reflejarlo hacia el atacante usando su propia tirada de ataque.")]),
    armor("cota_adamantina", "Cota de Adamantina", "Armadura Media", "Rara",
          7, "12 CR",
          "Malla forjada con adamantina, el metal más duro conocido. Los golpes que deberían ser devastadores apenas arañan su superficie.",
          type_="Armadura Mágica",
          props=["<b>Inquebrantable:</b> Los ataques críticos contra ti se convierten en impactos normales",
                 "<b>Indestructible:</b> Esta armadura no puede ser dañada por medios no mágicos"]),
    armor("escudo_leones", "Escudo de los Leones", "Escudo", "Rara",
          2, "8 CR",
          "Un escudo redondo de oro y acero con un león rugiente grabado. Símbolo de los comandantes leoninos de Arshalán.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>"],
          abilities=[ab("Rugido del León", "1 acción + 1 Vigor", "2/día",
                       "El león del escudo ruge. Todos los enemigos en 6m deben superar WILL o quedar con Miedo 1 durante 1 minuto. Aliados en 6m ganan +1d6 a su siguiente tirada de ataque.")]),
    armor("armadura_guardian", "Armadura del Guardián", "Armadura Pesada", "Rara",
          9, "12 CR",
          "Armadura de placas con runas protectoras grabadas en cada pieza. Emite un aura dorada tenue que se intensifica cuando aliados cercanos están en peligro.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>"],
          abilities=[ab("Aura Protectora", "Pasiva", "Permanente",
                       "Los aliados dentro de 3m reciben +1 a todas sus defensas."),
                    ab("Sacrificio del Guardián", "1 reacción", "3/día",
                       "Cuando un aliado adyacente recibiría daño, puedes recibir ese daño en su lugar.")],
          penalties="-6 a tiradas de DES. Velocidad -3m."),
]

# ─── RARE MAGIC ITEMS ───
ITEMS += [
    magic_item("anillo_hechizos", "Anillo de Almacenamiento", "Anillo", "Rara", "8 CR",
               "Un anillo de platino con una gema que cambia de color. En su interior se pueden almacenar ecos de poder mágico.",
               props=["<b>Sintonización</b>: Por un usuario de magia"],
               abilities=[ab("Almacenar Hechizo", "1 acción", "Ilimitado",
                            "Puedes almacenar hasta 3 puntos de Chi en el anillo. Posteriormente puedes usar ese Chi almacenado como si fuera propio.")]),
    magic_item("capa_desplazamiento", "Capa del Desplazamiento", "Maravilloso", "Rara", "8 CR",
               "Una capa de tela oscura que distorsiona la luz a su alrededor. Tu imagen parece estar siempre ligeramente desplazada de tu posición real.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Desplazamiento", "Pasiva", "Permanente",
                            "Los ataques contra ti tienen Desventaja. Si recibes daño, el efecto se desactiva hasta el inicio de tu siguiente turno.")]),
    magic_item("corona_sabiduria", "Corona de Sabiduría", "Maravilloso", "Rara", "10 CR",
               "Una diadema de plata con un zafiro central que brilla con luz interior. Los pensamientos del portador se aclaran al ponérsela.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Mente Clara", "Pasiva", "Permanente",
                            "Tu SAB se incrementa en +1 (hasta el máximo de tu nivel). Eres inmune a los efectos de Miedo 1 y 2."),
                          ab("Perspicacia", "1 acción + 1 Chi", "2/día",
                            "Puedes lanzar Detectar Magia sin coste de Chi ni acción de concentración.")]),
    magic_item("cinturon_gigante", "Cinturón del Gigante de Piedra", "Maravilloso", "Rara", "10 CR",
               "Un cinturón ancho de cuero con hebilla de granito tallada en forma de puño. Al ceñirlo, tus músculos crecen y la tierra responde a tus pisadas.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Fuerza de Gigante", "Pasiva", "Permanente",
                            "Tu FUE se considera 5 (sin efecto si ya es 5+). Puedes levantar y lanzar rocas como un ataque a distancia (2d8 contundente, distancia media).")]),
    magic_item("varita_misiles", "Varita de Proyectiles Arcanos", "Varita", "Rara", "6 CR",
               "Una varita de cristal translúcido con vetas de energía arcana visible en su interior. Dispara dardos de fuerza infalibles.",
               props=["<b>Sintonización</b>: Por un usuario de magia"],
               abilities=[ab("Proyectiles Arcanos", "1 acción", "7 cargas/día",
                            "Gasta 1-3 cargas. Por cada carga, un dardo de fuerza impacta automáticamente a un objetivo visible dentro de 18m, infligiendo 1d6+1 arcano. Se recargan 1d4+3 cargas al amanecer.")]),
    magic_item("botas_aladas", "Botas Aladas", "Maravilloso", "Rara", "10 CR",
               "Botas de cuero blanco con alas de pluma cosidas a los tobillos. Cuando se activan, las alas se materializan y permiten volar.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Vuelo", "1 acción", "3/día",
                            "Ganas velocidad de vuelo igual a tu velocidad de movimiento durante 10 minutos. Al finalizar, desciendes suavemente.")]),
    magic_item("collar_bolas_fuego", "Collar de Bolas de Fuego", "Maravilloso", "Rara", "8 CR",
               "Un collar de cuentas rojas y naranjas, cada una caliente al tacto. Contienen fuego comprimido que puede liberarse con devastadores resultados.",
               props=["<b>Consumible parcial:</b> Tiene 7 cuentas. Cada uso consume una cuenta"],
               abilities=[ab("Bola de Fuego", "1 acción", "7 cuentas",
                            "Arroja una cuenta a un punto dentro de 18m. Explota en un radio de 6m. Todos en el área deben superar PHYS o recibir 3d10 fuego (mitad en éxito). Puedes lanzar varias cuentas a la vez, sumando 1d10 por cuenta adicional.")]),
    magic_item("pergamino_proteccion", "Pergamino de Protección contra el Mal", "Pergamino", "Rara", "5 CR",
               "Un pergamino de vitela con oraciones protectoras escritas en tinta de plata. Al leerlo, una barrera invisible rodea al lector.",
               props=["<b>Consumible:</b> Se destruye al usarse"],
               abilities=[ab("Protección contra el Mal", "1 acción", "Una vez",
                            "Durante 10 minutos, no-muertos, demonios y diablos tienen Desventaja en ataques contra ti y no pueden poseerte ni encantarte.")]),
    magic_item("guantelete_poder", "Guantelete de Poder", "Maravilloso", "Rara", "10 CR",
               "Un guantelete de acero negro con cristales de Chi incrustados en los nudillos. Al cerrarlo, los cristales brillan con energía contenida.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Puño de Poder", "Pasiva", "Permanente",
                            "Tus ataques desarmados infligen 1d8 + FUE contundente (en vez de 1d6)."),
                          ab("Golpe Arcano", "1 acción + 2 Chi", "3/día",
                            "Tu puño se carga de energía arcana. Tu siguiente ataque desarmado inflige 3d8 arcano adicional.")]),
    magic_item("pocion_resistencia_fuego", "Poción de Resistencia al Fuego", "Poción", "Rara", "2 CR",
               "Un líquido azul gélido con copos de nieve suspendidos en su interior. Al beberla, un frío reconfortante recorre todo el cuerpo.",
               props=["<b>Consumible:</b> Se destruye al usarse"],
               abilities=[ab("Resistencia al Fuego", "1 acción", "Una vez",
                            "Durante 1 hora, ganas resistencia al daño de fuego (recibes la mitad de daño).")]),
    magic_item("baculo_elementos", "Báculo de los Elementos", "Báculo", "Rara", "12 CR",
               "Un báculo de madera petrificada con cuatro gemas: rubí, zafiro, topacio y esmeralda. Cada una contiene la esencia de un elemento.",
               props=["<b>Sintonización</b>: Por un usuario de magia elemental"],
               abilities=[ab("Canalizar Elemento", "1 acción + Chi variable", "10 cargas/día",
                            "Gasta cargas para lanzar: Muro de Fuego (4 cargas), Cono de Frío (4 cargas), Rayo (3 cargas), Temblor (2 cargas). Cada hechizo inflige 3d10 del tipo correspondiente. Se recargan 1d6+4 al amanecer.")]),
]

# ─── VERY RARE WEAPONS ───
ITEMS += [
    weapon("espada_vorpal", "Espada Vorpal", "Arma Marcial Cuerpo a Cuerpo", "Muy Rara",
           "2d6 + FUE", "Cortante", "30 CR",
           "Una espada de hoja imposiblemente afilada que corta a través de cualquier material. Su filo nunca se embota y brilla con una luz acerada.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>",
                  "<b>Decapitadora:</b> Cuando sacas un crítico natural en un ataque, el objetivo debe superar PHYS (CD 18) o ser decapitado (muerte instantánea si tiene cabeza y menos de 50 PV+VIT). Criaturas inmunes a críticos son inmunes a este efecto"]),
    weapon("arco_cazador_estelar", "Arco del Cazador Estelar", "Arma Marcial a Distancia", "Muy Rara",
           "1d10 + DES + 2d6 radiante", "Perforante + Radiante", "25 CR",
           "Un arco tallado en madera de un árbol celestial, con la cuerda hecha de luz solidificada. Las flechas brillan como estrellas fugaces.",
           range_="Distancia lejana",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>",
                  "<b>Infalible:</b> Puedes ver e impactar criaturas invisibles o en cobertura parcial sin penalización"],
           abilities=[ab("Lluvia de Estrellas", "2 acciones + 3 Chi", "1/día",
                        "Disparas una ráfaga de flechas luminosas. Hasta 6 objetivos dentro de 18m reciben 2d10 radiante cada uno (no requiere tirada de ataque).")]),
    weapon("martillo_titanes", "Martillo de los Titanes", "Arma Marcial Cuerpo a Cuerpo", "Muy Rara",
           "2d8 + FUE + 1d10 contundente", "Contundente", "30 CR",
           "Un martillo colosal forjado por gigantes ancestrales. Su cabeza está hecha de meteorito y pesa más de lo que cualquier mortal debería poder levantar.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>: Requiere FUE 5+",
                  "<b>Pesada</b>: Desventaja en tiradas de Parada", "<b>Aplastante:</b> Inflige daño doble a objetos y estructuras"],
           abilities=[ab("Golpe Titánico", "2 acciones + 3 Vigor", "1/día",
                        "Golpeas con toda la fuerza titánica. Inflige 6d10 contundente y el objetivo debe superar PHYS (CD 20) o quedar Aturdido 1 turno.")]),
    weapon("daga_planos", "Daga de los Planos", "Arma Simple Cuerpo a Cuerpo", "Muy Rara",
           "1d6 + DES + 1d8 arcano", "Perforante + Arcano", "20 CR",
           "Una daga cuya hoja parece estar en varios lugares a la vez. Al moverse, deja estelas que muestran otros planos de existencia.",
           range_="Cuerpo a cuerpo o arrojadiza (distancia media)",
           type_="Arma Mágica",
           props=["<b>Sintonización</b>", "<b>Interplanar:</b> Los ataques con esta daga afectan a criaturas etéreas e incorpóreas normalmente"],
           abilities=[ab("Corte Dimensional", "1 acción + 2 Chi", "2/día",
                        "Cortas el tejido entre planos. Te teleportas hasta 9m y haces un ataque al aparecer con Ventaja. Si impacta, inflige 3d8 arcano adicional."),
                     ab("Destierro", "2 acciones + 3 Chi", "1/día",
                        "Apuñalas a un objetivo que debe superar WILL (CD 18) o ser desterrado a un semiplano vacío durante 1 minuto. Al volver, aparece en el mismo lugar.")]),
    weapon("lanza_dragon", "Lanza Matadragones", "Arma Marcial Cuerpo a Cuerpo", "Muy Rara",
           "1d10 + FUE + 2d6 contra dragones", "Perforante", "25 CR",
           "Una lanza de mithrilo con punta de adamantina y runas antidraco grabadas a lo largo del asta. Vibra en presencia de sangre dracónica.",
           range_="Alcance cercano",
           type_="Arma Mágica",
           props=["<b>Sintonización</b>", "<b>Cazadora de Dragones:</b> Inflige 2d6 adicionales contra dragones y criaturas con sangre dracónica",
                  "<b>Resistencia Dracónica:</b> Mientras la portas, ganas resistencia al tipo de daño de aliento del último dragón que golpeaste"]),
    weapon("hacha_berserker", "Hacha del Berserker Eterno", "Arma Marcial Cuerpo a Cuerpo", "Muy Rara",
           "2d8 + FUE", "Cortante", "20 CR",
           "Un gran hacha de hierro oscuro manchada de sangre que nunca se seca. El portador siente una ira creciente que amenaza con consumirlo.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>",
                  "<b>Maldita:</b> Una vez sintonizado, no puedes desintonizar voluntariamente. Debes usar un ritual de purificación",
                  "<b>Sed de Sangre:</b> +1d6 de daño extra por cada enemigo que hayas matado en este combate (máx +3d6)"]),
    weapon("mosqueton_arcano", "Mosquetón Arcano", "Arma de Fuego", "Muy Rara",
           "2d8 + DES + 1d8 arcano", "Perforante + Arcano", "25 CR",
           "Un mosquetón iskariano modificado con cristales de Chi integrados en el cañón. Dispara proyectiles envueltos en energía arcana.",
           range_="Distancia lejana",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>",
                  "<b>Recarga Arcana:</b> Se recarga mágicamente, no requiere acción de recarga convencional",
                  "<b>Sin Fallos:</b> Inmune al efecto de encasquillamiento en 1 natural"]),
]

# ─── VERY RARE ARMOR ───
ITEMS += [
    armor("armadura_eterna", "Armadura Eterna", "Armadura Pesada", "Muy Rara",
          10, "30 CR",
          "Armadura de placas forjada con acero de meteorito que se repara sola. Las abolladuras y grietas se cierran lentamente como si el metal estuviera vivo.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>", "<b>Indestructible:</b> No puede ser dañada ni destruida por medios normales o mágicos"],
          abilities=[ab("Regeneración Metálica", "Pasiva", "Permanente",
                       "Al inicio de cada descanso corto, la armadura se repara cualquier daño cosmético. Si la armadura fuese de algún modo dañada mágicamente, se restaura en 24 horas.")],
          penalties="-6 a tiradas de DES. Velocidad -3m."),
    armor("escudo_absorcion", "Escudo de Absorción", "Escudo", "Muy Rara",
          2, "25 CR",
          "Un escudo de cristal negro translúcido que absorbe la energía de los ataques. Cada impacto lo hace brillar más intensamente.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>"],
          abilities=[ab("Absorber Energía", "1 reacción", "Ilimitado",
                       "Cuando recibes daño mágico, puedes usar tu reacción para absorber hasta 2d10 de ese daño. La energía se almacena."),
                    ab("Liberar Energía", "1 acción", "Ilimitado",
                       "Liberas toda la energía almacenada como un rayo en línea de 9m. Inflige daño igual al total absorbido (máximo 30). Resetea el almacenamiento.")]),
    armor("armadura_celestial", "Armadura Celestial", "Armadura Media", "Muy Rara",
          8, "35 CR",
          "Armadura de escamas blancas y doradas que emite un aura de paz. Forjada con metal de origen celestial, protege tanto el cuerpo como el alma.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>: Requiere alineación no malvada",
                 "<b>Sagrada:</b> Resistencia a daño necrótico"],
          abilities=[ab("Aura Celestial", "Pasiva", "Permanente",
                       "Eres inmune a efectos de Miedo y enfermedades. Aliados en 3m ganan +1d6 a salvaciones de WILL."),
                    ab("Alas de Luz", "1 acción + 2 Chi", "1/día",
                       "Alas luminosas brotan de la armadura. Ganas velocidad de vuelo igual a tu velocidad durante 1 hora.")],
          penalties="-2 a tiradas de DES."),
    armor("manto_archimago", "Manto del Archimago", "Armadura Ligera", "Muy Rara",
          3, "35 CR",
          "Una túnica de seda arcana que fluye con corrientes de energía visible. El tejido está entrelazado con hilos de pura magia cristalizada.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>: Por un usuario de magia",
                 "<b>Defensa Arcana:</b> Tu defensa mágica aumenta en +2 además de la DEF base"],
          abilities=[ab("Reserva Expandida", "Pasiva", "Permanente",
                       "Tu reserva máxima de Chi aumenta en +3."),
                    ab("Escudo Mágico", "1 reacción", "3/día",
                       "Cuando fallas una salvación contra un efecto mágico, puedes repetir la tirada con Ventaja.")]),
]

# ─── VERY RARE MAGIC ITEMS ───
ITEMS += [
    magic_item("anillo_regeneracion", "Anillo de Regeneración", "Anillo", "Muy Rara", "25 CR",
               "Un anillo de jade con vetas doradas que pulsan como un latido. La carne del portador se cierra y regenera con velocidad antinatural.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Regeneración", "Pasiva", "Permanente",
                            "Recuperas 1 punto de Vitalidad al inicio de cada uno de tus turnos si tienes al menos 1 PV. Además, miembros amputados se regeneran en 1d4 días.")]),
    magic_item("cristal_chi", "Cristal de Chi Primordial", "Maravilloso", "Muy Rara", "30 CR",
               "Un cristal de Chi del tamaño de un puño que late con energía primordial. Su brillo ilumina la habitación con luz arcana.",
               props=["<b>Sintonización</b>: Por un usuario de magia"],
               abilities=[ab("Reserva Primordial", "Pasiva", "Permanente",
                            "Tu reserva máxima de Chi aumenta en +5."),
                          ab("Sobrecarga", "Acción libre", "1/día",
                            "Cuando lanzas un hechizo o habilidad que cuesta Chi, puedes duplicar su efecto (dados de daño, duración o área) sin coste adicional de Chi.")]),
    magic_item("ojo_omnisciente", "Ojo Omnisciente", "Maravilloso", "Muy Rara", "30 CR",
               "Una esfera de cristal del tamaño de una manzana con un iris dorado en su centro. Al sostenerla, puedes percibir más allá de los sentidos normales.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Visión Verdadera", "1 acción + 2 Chi", "3/día",
                            "Durante 10 minutos, ves la forma verdadera de todo en 36m: invisibilidad, ilusiones, cambiaformas y puertas ocultas."),
                          ab("Escudriñar", "10 minutos + 3 Chi", "1/día",
                            "Observas a una criatura o lugar que conozcas, sin importar la distancia, durante 10 minutos. El objetivo puede sentir la observación con WILL (CD 18).")]),
    magic_item("alfombra_voladora", "Alfombra Voladora", "Maravilloso", "Muy Rara", "25 CR",
               "Una alfombra de seda con patrones geométricos que se mueven. Al sentarse y pronunciar la palabra de mando, se eleva silenciosamente.",
               abilities=[ab("Vuelo", "1 acción (palabra de mando)", "Ilimitado",
                            "La alfombra vuela a velocidad de 18m/turno y puede cargar hasta 3 personas o 300 kg. Obedece comandos verbales del propietario.")]),
    magic_item("espejo_dimension", "Espejo Dimensional", "Maravilloso", "Muy Rara", "30 CR",
               "Un espejo ovalado de marco plateado que no refleja la realidad sino otros lugares y tiempos. Su superficie ondula como agua.",
               abilities=[ab("Portal Espejo", "1 minuto + 3 Chi", "1/día",
                            "Convierte el espejo en un portal a cualquier lugar que hayas visitado. El portal permanece abierto 1 minuto y permite el paso en ambas direcciones."),
                          ab("Espiar", "1 acción + 1 Chi", "3/día",
                            "El espejo muestra cualquier lugar que conozcas en un radio de 10 km durante 10 minutos.")]),
    magic_item("tomo_conocimiento", "Tomo del Conocimiento Infinito", "Maravilloso", "Muy Rara", "35 CR",
               "Un libro grueso con tapas de metal antiguo cuyas páginas están en blanco hasta que se formula una pregunta. La respuesta aparece escrita.",
               props=["<b>Sintonización</b>"],
               abilities=[ab("Consultar", "1 acción", "3/día",
                            "Formula una pregunta sobre historia, geografía, magia o criaturas. El tomo proporciona la respuesta más precisa disponible (a discreción del DJ). No puede revelar el futuro ni secretos protegidos mágicamente."),
                          ab("Estudio Acelerado", "8 horas", "1/semana",
                            "Estudias el tomo durante un descanso largo. Ganas competencia temporal en una habilidad de conocimiento de tu elección durante 1 semana.")]),
]

# ─── LEGENDARY WEAPONS ───
ITEMS += [
    weapon("espada_feyn", "Espada de Feyn", "Arma Marcial Cuerpo a Cuerpo", "Legendaria",
           "2d6 + FUE + 2d8 radiante", "Cortante + Radiante", "100 CR",
           "La legendaria espada que Feyn portó cuando descendió al mundo. Su hoja es de luz solidificada y su empuñadura muestra el símbolo del primer imperio. Nadie la ha visto desde la Desaparición.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos",
                  "<b>Sintonización</b>: Solo puede ser empuñada por alguien de corazón puro (a criterio del DJ)",
                  "<b>Artefacto</b>: No puede ser destruida por medios convencionales"],
           abilities=[ab("Juicio de Feyn", "2 acciones + 3 Chi", "1/día",
                        "La espada emite un estallido de luz divina. Todos los enemigos en 12m deben superar WILL (CD 22) o recibir 6d10 radiante y quedar Cegados 1 turno. No-muertos y demonios reciben el doble."),
                     ab("Aura del Primer Rey", "Pasiva", "Permanente",
                        "Mientras empuñas la espada, eres inmune a Miedo, encantamiento y posesión. Aliados en 9m ganan +1d6 a todas sus salvaciones."),
                     ab("Luz Eterna", "Pasiva", "Permanente",
                        "La espada emite luz brillante en 9m y luz tenue en 18m. Esta luz no puede ser apagada por ningún medio mágico.")],
           lore="Se dice que Feyn dejó su espada oculta para quien la mereciera cuando el mundo la necesitase de nuevo. Los Caballeros de Ustilus la han buscado durante una década."),
    weapon("arco_estrellas", "Arco de las Estrellas", "Arma Marcial a Distancia", "Legendaria",
           "1d10 + DES + 3d6 radiante", "Perforante + Radiante", "80 CR",
           "Un arco forjado con fragmentos de estrellas caídas. Su cuerda es un rayo de luz lunar y las flechas que dispara son constelaciones comprimidas.",
           range_="Distancia lejana (sin límite máximo de noche)",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>",
                  "<b>Artefacto</b>", "<b>Nocturno:</b> De noche, el alcance del arco es ilimitado (si puedes ver el objetivo)"],
           abilities=[ab("Constelación Cazadora", "2 acciones + 4 Chi", "1/día",
                        "Tres flechas de luz estelar persiguen a un objetivo, impactando automáticamente por 3d10+3d6 radiante cada una. El objetivo no puede ser invisible ni estar en cobertura."),
                     ab("Lluvia Meteórica", "3 acciones + 5 Chi", "1/semana",
                        "Invocas una lluvia de meteoritos en un área de 18m de radio a 36m de distancia. Todos en el área reciben 8d10 fuego + radiante. PHYS (CD 22) para mitad.")]),
    weapon("martillo_mundo", "Martillo del Mundo", "Arma Marcial Cuerpo a Cuerpo", "Legendaria",
           "2d8 + FUE + 2d8 contundente", "Contundente", "100 CR",
           "Un martillo primordial cuya cabeza está tallada de un fragmento del primer monte del mundo. Cada golpe tiene la fuerza de un terremoto.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>: Requiere FUE 6+",
                  "<b>Artefacto</b>", "<b>Inamovible:</b> Nadie sin la fuerza requerida puede siquiera levantarlo"],
           abilities=[ab("Cataclismo", "3 acciones + 5 Vigor", "1/día",
                        "Golpeas el suelo con toda la fuerza del mundo. Todos los enemigos en 18m deben superar PHYS (CD 22) o recibir 10d10 contundente y quedar Tropezados y Aturdidos 1 turno. Estructuras y objetos en el área son destruidos."),
                     ab("Lanzamiento del Titán", "2 acciones + 3 Vigor", "3/día",
                        "Arrojas el martillo a un objetivo a distancia lejana. Inflige 6d10 contundente y el martillo regresa a tu mano.")]),
    weapon("guadana_muerte", "Guadaña de la Muerte", "Arma Marcial Cuerpo a Cuerpo", "Legendaria",
           "2d6 + FUE + 2d8 necrótico", "Cortante + Necrótico", "80 CR",
           "Una guadaña forjada con hueso de una criatura olvidada y metal del Plano Sombrío. Las almas de los caídos giran en torno a su hoja como mariposas espectrales.",
           type_="Arma Mágica",
           props=["<b>Dos manos</b>: Requiere ambas manos", "<b>Sintonización</b>: Por un usuario de Nigromancia",
                  "<b>Artefacto</b>", "<b>Cosechadora:</b> Cuando reduces a un enemigo a 0 PV, recuperas 2d10 de Vitalidad"],
           abilities=[ab("Segar Almas", "2 acciones + 3 Chi", "3/día",
                        "En un arco de 6m, todos los enemigos reciben 4d10 necrótico. Por cada enemigo golpeado, ganas 5 de Vitalidad temporal."),
                     ab("Invocar Espectro", "2 acciones + 4 Chi", "1/día",
                        "El alma del último enemigo muerto por la guadaña se levanta como un Espectro bajo tu control durante 1 hora.")],
           lore="Se rumorea que fue forjada en la Brecha Abisal y que la Madre del Abismo misma bendijo su filo."),
    weapon("lanza_destino", "Lanza del Destino", "Arma Marcial Cuerpo a Cuerpo", "Legendaria",
           "1d10 + FUE + 2d6 divino", "Perforante + Divino", "100 CR",
           "Una lanza de oro blanco que parece vibrar con el pulso del universo. Quien la empuña siente el peso del destino sobre sus hombros.",
           range_="Alcance cercano o arrojadiza (cualquier distancia visible)",
           type_="Arma Mágica",
           props=["<b>Sintonización</b>", "<b>Artefacto</b>",
                  "<b>Certera:</b> +3 a todas las tiradas de ataque con esta arma",
                  "<b>Destino Ineludible:</b> Cuando arrojada, la lanza persigue a su objetivo y no puede ser esquivada (solo bloqueada o parada)"],
           abilities=[ab("Golpe del Destino", "2 acciones + 4 Chi", "1/día",
                        "La lanza brilla con luz divina. El siguiente ataque ignora todas las resistencias, inmunidades y defensas del objetivo. Inflige daño normal + 4d10 divino."),
                     ab("Retorno", "Acción libre", "Ilimitado",
                        "La lanza regresa volando a tu mano al final de tu turno, sin importar la distancia.")]),
]

# ─── LEGENDARY ARMOR ───
ITEMS += [
    armor("armadura_dioses", "Armadura de los Dioses", "Armadura Pesada", "Legendaria",
          12, "100 CR",
          "Una armadura resplandeciente de metal divino que parece hecha de amanecer solidificado. Fue forjada antes de la Guerra de los Dioses y pocos mortales la han vestido.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>", "<b>Artefacto</b>",
                 "<b>Divina:</b> Inmunidad a daño necrótico y veneno",
                 "<b>Irrompible:</b> No puede ser dañada ni destruida"],
          abilities=[ab("Escudo Divino", "Pasiva", "Permanente",
                       "Resistencia a todo daño mágico. +3 a todas las salvaciones."),
                    ab("Intervención Divina", "1 reacción", "1/día",
                       "Cuando recibirías daño que te reduciría a 0 PV, en su lugar quedas con 1 PV y el daño se anula completamente.")],
          penalties="Ninguna. La armadura no tiene penalizaciones."),
    armor("escudo_invencible", "Escudo Invencible", "Escudo", "Legendaria",
          4, "60 CR",
          "Un escudo circular de adamantina pura con runas de protección de los Primeros Dioses grabadas en su superficie. Ningún golpe lo ha agrietado jamás.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>", "<b>Artefacto</b>",
                 "<b>Impenetrable:</b> +3 a DEF adicional contra ataques a distancia"],
          abilities=[ab("Muro Inamovible", "1 acción", "3/día",
                       "Plantas el escudo y creas una barrera mágica de 6m de ancho que bloquea todo movimiento y proyectiles durante 1 minuto. La barrera tiene 50 PV."),
                    ab("Contraataque Perfecto", "1 reacción", "Ilimitado",
                       "Cuando un ataque cuerpo a cuerpo contra ti falla, puedes hacer un ataque de escudo inmediato (2d8+FUE contundente).")]),
    armor("corona_emperador", "Corona del Emperador Eterno", "Armadura Ligera", "Legendaria",
          2, "80 CR",
          "Una corona de platino con siete gemas que representan las siete virtudes del primer imperio. Quien la porte irradia una autoridad que trasciende la mortalidad.",
          type_="Armadura Mágica",
          props=["<b>Sintonización</b>", "<b>Artefacto</b>"],
          abilities=[ab("Autoridad Absoluta", "1 acción + 3 Chi", "3/día",
                       "Emites un comando que todos los que te escuchen en 18m deben superar WILL (CD 22) o obedecer durante 1 turno. No funciona contra criaturas inmunes a encantamiento."),
                    ab("Presencia Imperial", "Pasiva", "Permanente",
                       "Tu CAR se incrementa en +2 (hasta el máximo de tu nivel). Eres inmune a Miedo y encantamiento. Aliados en 9m ganan +1d6 a tiradas de WILL."),
                    ab("Inmortalidad del Trono", "Pasiva", "Permanente",
                       "Mientras lleves la corona, no envejeces y eres inmune a enfermedades y venenos.")]),
]

# ─── LEGENDARY MAGIC ITEMS ───
ITEMS += [
    magic_item("orbe_dominacion", "Orbe de Dominación", "Maravilloso", "Legendaria", "80 CR",
               "Una esfera de obsidiana del tamaño de un puño envuelta en llamas frías. Susurra promesas de poder a quien la toca. Se dice que fue creada por Sek-Tebos.",
               props=["<b>Sintonización</b>", "<b>Artefacto</b>",
                      "<b>Maldito:</b> Mientras estés sintonizado, tu alineación se vuelve gradualmente más oscura. Desintonizar requiere un ritual de purificación de nivel 5+"],
               abilities=[ab("Dominar Voluntad", "2 acciones + 4 Chi", "3/día",
                            "Un objetivo dentro de 18m debe superar WILL (CD 22) o quedar bajo tu control durante 1 hora. Si el objetivo sufre daño, puede repetir la salvación. Criaturas con INT 7+ tienen Ventaja en la salvación."),
                          ab("Aura de Terror", "1 acción + 2 Chi", "Ilimitado",
                            "Todos los enemigos en 9m deben superar WILL (CD 20) o quedar con Miedo 3 durante 1 minuto.")],
               lore="Los eruditos creen que este orbe es uno de los instrumentos que Sek-Tebos usó para corromper civilizaciones enteras. Poseerlo es peligroso, pero su poder es innegable."),
    magic_item("anillo_deseos", "Anillo de los Deseos", "Anillo", "Legendaria", "200 CR",
               "Un anillo de oro puro sin adornos que brilla con todos los colores del espectro. En su interior está inscrita una única palabra en el idioma de la creación.",
               props=["<b>Sintonización</b>", "<b>Artefacto</b>"],
               abilities=[ab("Deseo", "1 acción", "1d4 cargas (no recargables)",
                            "Puedes formular un deseo. El DJ interpreta el deseo de la forma más razonable posible. Usos típicos: replicar cualquier hechizo, restaurar a un muerto, alterar la realidad de forma limitada. Cada uso tiene un 33% de probabilidad de que el anillo se desintegre."),
                          ab("Deseo Menor", "1 acción", "3/día",
                            "Puedes replicar el efecto de cualquier habilidad mágica de Rango III o inferior sin coste de Chi.")]),
    magic_item("amuleto_inmortalidad", "Amuleto de la Inmortalidad", "Maravilloso", "Legendaria", "100 CR",
               "Un amuleto de jade negro con un corazón humano grabado que late tenuemente. Mientras lo portes, la muerte no puede reclamarte... al menos no permanentemente.",
               props=["<b>Sintonización</b>", "<b>Artefacto</b>"],
               abilities=[ab("Inmortalidad Condicional", "Pasiva", "Permanente",
                            "No envejeces. Si mueres, tu cuerpo se reconstruye en 1d4 días en el lugar donde caíste (a menos que tu cuerpo sea completamente desintegrado o el amuleto sea destruido)."),
                          ab("Vitalidad Eterna", "Pasiva", "Permanente",
                            "Tu máximo de PV aumenta en +5. Eres inmune a enfermedades, venenos y efectos de envejecimiento.")]),
    magic_item("baculo_archimago_supremo", "Báculo del Archimago Supremo", "Báculo", "Legendaria", "80 CR",
               "Un báculo de cristal vivo que cambia de forma según el usuario. Contiene un núcleo de Chi concentrado que late como un corazón.",
               props=["<b>Sintonización</b>: Por un usuario de magia con Rango IV+ en cualquier escuela",
                      "<b>Artefacto</b>"],
               abilities=[ab("Poder Supremo", "Pasiva", "Permanente",
                            "Tu reserva máxima de Chi aumenta en +8. Todos tus hechizos infligen +1d8 de daño adicional de su tipo."),
                          ab("Canalización Perfecta", "Acción libre", "3/día",
                            "Cuando lanzas un hechizo que requiere Chi, puedes reducir su coste en 3 (mínimo 0)."),
                          ab("Rayo del Archimago", "2 acciones + 5 Chi", "1/día",
                            "Disparas un rayo devastador de energía arcana pura. Línea de 30m, 8d10 arcano. WILL (CD 22) para mitad.")]),
    magic_item("libro_sombras", "Libro Vil de la Oscuridad", "Maravilloso", "Legendaria", "60 CR",
               "Un tomo encuadernado en piel de demonio con páginas de pergamino negro escritas con sangre luminiscente. Contiene secretos prohibidos de nigromancia y magia abisal.",
               props=["<b>Sintonización</b>: Por un usuario de Nigromancia o Magia Sombría",
                      "<b>Artefacto</b>", "<b>Maldito:</b> Leerlo reduce tu Cordura en 1 por cada hora de estudio"],
               abilities=[ab("Conocimiento Prohibido", "8 horas", "1/semana",
                            "Al estudiar el libro durante un descanso largo, puedes aprender temporalmente una habilidad de Nigromancia o Magia Sombría de hasta Rango V durante 1 semana."),
                          ab("Invocar Horror", "3 acciones + 5 Chi + 2 Cordura", "1/día",
                            "Invocas una criatura abisal o no-muerta de nivel 10 o inferior que obedece tus órdenes durante 1 hora.")],
               lore="Se dice que fue escrito por un nigromante de Hakrapeu que canalizaba la voz de la Madre del Abismo. Varias copias existen, cada una ligeramente diferente."),
    magic_item("cuerno_guerra", "Cuerno de Guerra de los Valientes", "Maravilloso", "Legendaria", "50 CR",
               "Un cuerno de guerra tallado en colmillo de dragón antiguo con bandas de oro. Su sonido puede escucharse a kilómetros y despierta el valor en los corazones aliados.",
               props=["<b>Artefacto</b>"],
               abilities=[ab("Llamada a las Armas", "1 acción", "1/día",
                            "Al soplar el cuerno, 3d6 guerreros espectrales aparecen y luchan a tu lado durante 1 hora. Son guerreros de nivel 6 con equipo estándar."),
                          ab("Grito de Victoria", "1 acción", "3/día",
                            "Todos los aliados que escuchen el cuerno (18m) recuperan 2d10 de Vitalidad y quedan inmunes a Miedo durante 1 minuto.")]),
    magic_item("guantelete_infinito", "Guantelete del Infinito", "Maravilloso", "Legendaria", "200 CR",
               "Un guantelete de oro con seis engarces para gemas cósmicas. Incluso vacío, otorga poder sobre la realidad. Completo, su portador sería como un dios.",
               props=["<b>Sintonización</b>", "<b>Artefacto</b>",
                      "<b>Incompleto:</b> El guantelete tiene 6 engarces. Cada gema cósmica (artefactos separados) añade un poder. Sin gemas, solo otorga el poder base"],
               abilities=[ab("Poder Base", "Pasiva", "Permanente",
                            "Tu FUE se considera 7 mientras portes el guantelete. Tus ataques desarmados con esa mano infligen 2d10+FUE contundente."),
                          ab("Chasquido (6 gemas)", "1 acción", "Una vez",
                            "Si las seis gemas cósmicas están engarzadas, puedes alterar la realidad a escala masiva. El esfuerzo destruye el guantelete y te reduce a 1 PV permanente durante 1 año.")]),
    magic_item("piedra_filosofal", "Piedra Filosofal", "Maravilloso", "Legendaria", "150 CR",
               "Una piedra cristalina roja que parece contener un universo en miniatura en su interior. Los alquimistas han buscado su secreto durante milenios.",
               props=["<b>Sintonización</b>", "<b>Artefacto</b>"],
               abilities=[ab("Transmutación", "1 hora", "Ilimitado",
                            "Puedes transmutar hasta 1 kg de cualquier material no mágico en otro material (plomo en oro, piedra en diamante, etc.)."),
                          ab("Elixir de la Vida", "8 horas", "1/mes",
                            "Creas una dosis de Elixir de la Vida. Quien lo beba rejuvenece 10 años, cura todas las enfermedades y heridas permanentes, y gana +1 permanente a CON (máximo según nivel)."),
                          ab("Perfección Alquímica", "1 acción + 2 Chi", "3/día",
                            "Tocas una poción y duplicas su efecto o duración.")]),
    magic_item("reliquia_mekhatim", "Reliquia de Mekhatim", "Maravilloso", "Legendaria", "100 CR",
               "Un fragmento del primer Taurenet escrito por la mano de Mekhatim. La vitela está imbuida con energía celestial y las letras brillan con luz dorada.",
               props=["<b>Sintonización</b>", "<b>Artefacto</b>",
                      "<b>Sagrada:</b> Solo puede ser usada por alguien que siga el camino de Mekhatimismo o tenga alineación buena"],
               abilities=[ab("Detectar Corrupción", "Pasiva", "Permanente",
                            "Puedes detectar la influencia del Culto de Sek-Tebos y otros cultos corruptos. Percibes Pactos del Servicio y manipulación demoníaca en un radio de 30m."),
                          ab("Purificación", "2 acciones + 3 Chi", "1/día",
                            "Purificas un Pacto del Servicio, liberando el alma atrapada. El objetivo debe estar dispuesto o incapacitado."),
                          ab("Palabra Celestial", "3 acciones + 5 Chi", "1/semana",
                            "Invocas la protección de la Hueste Celestial. Un ángel de nivel 12 desciende y te asiste durante 1 hora.")],
               lore="De los fragmentos originales del Taurenet, se cree que solo quedan tres. Uno está en Beisyan, otro perdido, y el tercero... nadie sabe."),
    magic_item("mascara_mil_rostros", "Máscara de los Mil Rostros", "Maravilloso", "Legendaria", "60 CR",
               "Una máscara blanca sin rasgos que se adapta al rostro de quien la porte. Cuando se activa, el portador puede asumir cualquier identidad.",
               props=["<b>Sintonización</b>", "<b>Artefacto</b>"],
               abilities=[ab("Cambio de Rostro", "1 acción", "Ilimitado",
                            "Asumes la apariencia exacta de cualquier humanoide que hayas visto, incluyendo voz, olor y mannerismos. La transformación es física, no ilusoria. Dura hasta que la desactives."),
                          ab("Robar Recuerdos", "1 acción + 3 Chi", "1/día",
                            "Al tocar a un humanoide incapacitado o dispuesto, copias sus últimas 24 horas de recuerdos, incluyendo conocimientos, contraseñas y planes."),
                          ab("Invisibilidad", "1 acción + 1 Chi", "3/día",
                            "Te vuelves completamente invisible durante 10 minutos o hasta que ataques.")]),
]

# ═══════════════════════════════════════════════════════════════
# MAIN
# ═══════════════════════════════════════════════════════════════

def main():
    os.makedirs(OUT_DIR, exist_ok=True)
    count = 0
    by_rarity = {}
    for item in ITEMS:
        write_item(item)
        count += 1
        r = item.get("rarity", "?")
        by_rarity[r] = by_rarity.get(r, 0) + 1

    print(f"Generated {count} items in {OUT_DIR}")
    for r in ["Común", "Poco Común", "Rara", "Muy Rara", "Legendaria"]:
        print(f"  {r}: {by_rarity.get(r, 0)}")

if __name__ == "__main__":
    main()
